version: '2'
services:
    moneys-app:
        image: moneys
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://moneys-postgresql:5432/moneys
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    moneys-postgresql:
        extends:
            file: postgresql.yml
            service: moneys-postgresql
